param([switch]$Execute)

$ErrorActionPreference = "Stop"
$serverRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$dataRoot = (Resolve-Path (Join-Path $serverRoot "data")).Path
$hourlyRoot = (Resolve-Path (Join-Path $serverRoot "data3")).Path
$reportsRoot = (Resolve-Path (Join-Path $serverRoot "reports")).Path

# Preserve raw files required to reproduce the 1/3/6-month experiments.
$targets = @()
$targets += Get-ChildItem -LiteralPath $dataRoot -File |
    Where-Object { $_.Extension -eq ".csv" -and $_.BaseName -notmatch "^data_25(06|07|08|09|10|11|12)$" }
$targets += Get-ChildItem -LiteralPath $hourlyRoot -File |
    Where-Object { $_.Extension -eq ".csv" -and $_.BaseName -notmatch "_2025(06|07|08|09|10|11|12)$" }

# UsageRepository reads CSV only.
$targets += Get-ChildItem -LiteralPath (Join-Path $dataRoot "usage") -File -Filter "*.xlsx"

# These intermediate outputs are regenerated by the ML pipeline.
$processedRoot = Join-Path $dataRoot "ml_processed"
if (Test-Path -LiteralPath $processedRoot) {
    $targets += Get-ChildItem -LiteralPath $processedRoot -File
}
$edaRoot = Join-Path $reportsRoot "eda"
if (Test-Path -LiteralPath $edaRoot) {
    $targets += Get-ChildItem -LiteralPath $edaRoot -File
}

$targets = $targets | Sort-Object FullName -Unique
$allowedRoots = @($dataRoot, $hourlyRoot, $reportsRoot)
foreach ($target in $targets) {
    $isAllowed = $false
    foreach ($allowedRoot in $allowedRoots) {
        if ($target.FullName.StartsWith($allowedRoot + "\")) {
            $isAllowed = $true
            break
        }
    }
    if (-not $isAllowed) {
        throw "Target outside allowed roots: $($target.FullName)"
    }
}

$totalBytes = ($targets | Measure-Object Length -Sum).Sum
Write-Host "Candidates: $($targets.Count) files"
Write-Host ("Expected savings: {0:N2} GB" -f ($totalBytes / 1GB))
$targets | Group-Object DirectoryName | ForEach-Object {
    Write-Host ("  {0} files  {1}" -f $_.Count, $_.Name)
}

if (-not $Execute) {
    Write-Host "Preview only. Delete with: .\scripts\cleanup_unused_data.ps1 -Execute"
    exit 0
}

foreach ($target in $targets) {
    Remove-Item -LiteralPath $target.FullName -Force
}
Write-Host "Deleted: $($targets.Count) files"
